version: '2'
services:
  spring-boot-jdk:
    build:
        context: .
        args:
            JAR_FILE: "sb-rest-service-8.jar"
    image: "spring-boot-jdk"
    container_name: spring-boot-jdk
    ports:
    - "8080:8080"
    networks:
            - dockernet
networks:
    dockernet:
        driver: bridge
        ipam:
            config:
            - subnet: 192.168.0.0/24
              gateway: 192.168.0.1
